### ISSUE TITLE
Problems with IMAP IDLE

### ISSUE THREAD

**Issue by sport80** [christianbur/docker_projects#13]
Hi, i'm using your solution with mailcow as a lot of time without problems with an Italian ISP (aruba.it) that manage my private domain but from (araund) the 20th of february, the getmail can't sync correctly. The firts login works correctly and it gets the lastest received emails but the imap idle seems that it can't say to the daemon that a new email has arrived so it don't download nothing and i can't see the notification of the new email.
I've tried many test and i'm pretty sure that it could be an incorrect or a missing feature of the implementation of the imap idle protocol, i've also contacted the (payment) support of the ISP but without success.

The mailbox(es) in your getmail implementation remain in the status "INFO: Join infinite loop and wait for new mails, cancel with Ctrl-c" without receiving nothing. The same result occours using my private domain but also using a free and generic domain @aruba.it
I've also tried with another free email provider (eg: libero.it) and in this case getmail it works correctly. Enabling the imap debug does not have any effect and i can't see any type of error.
The same problem (obviously only for test or comparison) occours using the email in Outlook 2019, that, connected directly to the imap of the ISP, it can't see the new email reveived if it remain in inbox, changing the folder (eg: from INBOX to Draft ad back to INBOX) it "renew" the connection and it can receive the email.

I've also tried with or without the SSL but without success. I've also tried using the openssl login to the email to emulating and manual  enabling the imap idle connection and apparently it seems that the feature is enabled but the only signal that i receive when an email is delivered to the mailbox is a generic "* OK Still here"

The only difference that i've find between the two previous examples aruba.it and libero.it is that aruba.it use a TLS 1.3 and libero.it a TLS 1.2

If you have an idea it would be appreciated. For now the only solution for me is to enable the sync job integrated in mailcow.

Thank you very much for your support and sorry for my bad english

Best regards

**Comment by christianbur** [comment]
I think the problem has nothing to do with the encryption (TLS).
The Imap server should also support IMAP Idle, otherwise an error would generate [here.](https://github.com/christianbur/docker_projects/blob/33facd3fb932f358e60abf6a43899db65f2ab49e/getmail/Dockerfiles/getmail_imap2lmtp.py#L79) 
With the following command line (e.g. inserted in line 81 of the script) you can display the capabilities of the IMAP server, here 'IDLE' will surely appear. 
      `logging.info("Login - capabilities: %s" % str(self.imap.capabilities()))`

`* OK Still here" ` indicates an active imap idle session, I also [catch this response](https://github.com/christianbur/docker_projects/blob/33facd3fb932f358e60abf6a43899db65f2ab49e/getmail/Dockerfiles/getmail_imap2lmtp.py#L137) in the script, but I don't know why anymore. 

However, without a test account I don't know how to analyze the problem. 

english tip: https://www.deepl.com/translator

**Comment by sport80** [comment]
Hi, thank you for your reply. As i've writed before, the problem occours both using a private mailbox account or a free and generic email address @aruba.it. If you prefer a test mailbox from my domain I can create it for you, no problem.

**Comment by christianbur** [comment]
Then create a mailbox for me. Mail to 
mail at christian-burmeister . de

**Comment by sport80** [comment]
Ok, email account created, have you received my email?

**Comment by christianbur** [comment]
I received the email, I'll take a look at it tonight.

**Comment by christianbur** [comment]
I could not find any error, I sent myself three test emails and they were fetched fine with getmail. 
I have sent you the logs by email.

**Comment by sport80** [comment]
So the problem is mine alone. I'm sorry for the inconvenience. I've tried all possible solutions but I can't figure out what's not working.
This evening I removed and reinstalled your docker image by redownloading the alpine base image and it's dependencies but I can't get it to work. It seems that after the first connection it is no longer able to understand the IMAP IDLE connection. 
In the tests that I've done I've also killed the connections manually on the firewall and blocked the traffic to the IMAP server. 
I also tried to restarting the firewall but getmail never failed as if it never noticed that I had disconnected it from the IMAP server.  Getmail it's installed on a standard Debian 10 VM.
I'll do some more testing even if I can't figure out why instead with a different IMAP server I don't have these problems. 

Thanks a lot and sorry again

**Comment by christianbur** [comment]
I had such a behavior before, at that time it was due to an email with strange special characters. 

With "imap_sync_folder:  INBOX" you define the folder which should be fetched by getmail. If necessary create a new folder "TEST" and then use this for testing.

```
[testmail_sxxxx_to_it]
imap_hostname:     imaps.aruba.it
imap_username:     testmail@sxxxx.to.it
imap_password:     xxxxxxxxxxxxxxxx
imap_sync_folder:  TEST
```


Then the logs (# docker compose logs), with activated debugging in the settings.ini, would also be helpful. 

```
imap_debug:        True
lmtp_debug:        True
```
