### ISSUE TITLE
mailcow did not connect to network-getmail

### ISSUE THREAD

**Issue by s4069b** [christianbur/docker_projects#9]
I needed to run this command: "docker network connect network-getmail  mailcowdockerized_dovecot-mailcow_1" to get mailcow to connect to network-getmail (verified connection with: "docker network inspect network-getmail"

And of course then needed to make sure settings.ini specified "lmtp_hostname:     mailcowdockerized_dovecot-mailcow_1" in the default section. 

Everything worked then, just testing it out now.

**Comment by christianbur** [comment]
I suspect you didn't put the docker-compose.override.yml file in the mailcow folder, because this maps the dovecot-mailcow conainter to the network network-getmail and can also be accessed in DNS under dovecot-mailcow. 

```
root@server0:/data/docker_projects# ls -al mailcow-dockerized/docker*
-rw-r--r-- 1 root root   244 Jun  4 08:41 mailcow-dockerized/docker-compose.override.yml
-rw-r--r-- 1 root root 22464 Jun  4 08:41 mailcow-dockerized/docker-compose.yml
```

https://github.com/christianbur/docker_projects/blob/master/getmail/mailcow-dockerized_docker-compose.override.yml

**Comment by s4069b** [comment]
oops. I introduced a typo into the file name: docker-compose-override.yml
fixed that, and yes. Correct. Everything worked - with "lmtp_hostname: dovecot-mailcow".  My mistake.
